### PR TITLE
Custom triggers

### PR DESCRIPTION
**Pull request by ner0-m**
This is a first attempt to support custom triggers. Now custom triggers can be set up using the configuration. I tried to make it as easy as possible to get any information and so far I've reduced it to two lines to get anything, which I think is okay.

Any feedback and suggestions are welcome :-)

### CODE REVIEW

**Comment by petertriho** [comment]
This is looking good!

**Comment by ner0-m** [comment]
I don't have a particular opinion on a global config. But I do prefer having a config table passed to each call (such as the `get_commits` one), such that the global config can be easily overwritten without restoring and changing it every call.

But for now I'll clean some things up.

**Comment by ner0-m** [comment]
From my side this is done. If you (@petertriho) don't have anything to add, I'll squash the commits and merge it. I have some refactoring ideas which I would like to do after this, but this is quite large already

**Comment by petertriho** [comment]
Everything looks ready to merge from me

**Pull request merged**
